import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'


export default function Home() {

  const handleBannerBtnClick = () => {
    console.log('Button clicked!');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shoppe: Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View Nearby Stores" handleOnClick={handleBannerBtnClick} />
      </main>

      <footer className={styles.footer}>
        © 2022 Coffee Connoisseur
      </footer>
    </div>
  )
}
