import Head from "next/head"
import Image from "next/image"
import Banner from "../components/Banner"
import Card from "../components/Card"

import coffeeStoresData from "../data/coffee-stores.json"
import styles from "../styles/Home.module.css"

export async function getStaticProps() {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  const handleBannerBtnClick = () => {
    console.log("Button clicked!")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shoppe</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Nearby Stores"
          handleOnClick={handleBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Hero Image"
            width={700}
            height={400}
          />
        </div>

        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((store) => {
                return (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/coffee-store/${store.id}`}
                  />
                )
              })}
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>© 2022 Coffee Connoisseur</footer>
    </div>
  )
}
